version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Frontend/IsCream/nginx.conf:/etc/nginx/nginx.conf  # 정확한 경로로 수정
      - ./Frontend/IsCream/build:/usr/share/nginx/html       # React 빌드 파일 경로
      - /etc/letsencrypt:/etc/letsencrypt                   # SSL 인증서 경로
    depends_on:
      - backend
      - ai-server   

  backend:
    build:
      context: ./Backend/IsCream
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    build:
      context: ./Frontend/IsCream
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    # volumes 항목은 삭제 (frontend는 nginx 설정과 별도로 작동하므로 불필요)

  ai-server:
    build:
      context: ./AI
      dockerfile: Dockerfile
    container_name: ai-server
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/models:/home/ubuntu/models  # 모델 경로 마운트
