version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
      - ai-server

  frontend:
    build:
      context: ./Frontend/IsCream
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    volumes:
      - ./Frontend/IsCream/build:/usr/share/nginx/html  # 빌드 파일 공유

  backend:
    build:
      context: ./Backend/IsCream
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  ai-server:
    build:
      context: ./AI
      dockerfile: Dockerfile
    container_name: ai-server
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/models:/home/ubuntu/models
