version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # 📌 루트 nginx.conf 사용
      - ./Frontend/IsCream/build:/usr/share/nginx/html  # React 빌드 파일 사용
      - /etc/letsencrypt:/etc/letsencrypt  # SSL 인증서 경로
    depends_on:
      - frontend  # 📌 frontend가 먼저 실행되어야 함
      - backend
      - ai-server

  frontend:
    build:
      context: ./Frontend/IsCream
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    depends_on:
      - backend  # 📌 백엔드 실행 후 프론트 실행 (필요 시)

  backend:
    build:
      context: ./Backend/IsCream
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  ai-server:
    build:
      context: ./AI
      dockerfile: Dockerfile
    container_name: ai-server
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/models:/home/ubuntu/models  # 모델 경로 마운트
